name: kafka-hands-on-experiment-ci-cd

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v2
      - name: setup java 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: maven package
        run: mvn -B clean package -DskipTests
      - name: maven verify
        run: mvn -B clean verify
